### ISSUE TITLE
No proxy connection message

### ISSUE THREAD

**Issue by afaik4711** [addstar/geSuit#11]
Hey!
Thanks for continuing the geSuit.
Works perfectly, except for the proxy connection message.
PLAYER_CONNECT_PROXY <- is not displayed
PLAYER_DISCONNECT_PROXY <- is displayed
As you see, the disconnect message is displayed in the chat. Sadly, I don't have another plugin for bungeewide connection messages. 
It would be really nice of you, if you could look into it.

Thanks a lot.
afaik4711

**Comment by addstar** [comment]
Sorry, forgot to respond to this. Closing old issue.
If you are still having the problem, please re-open with more information (including full console logs and an explanation). Please also mention the build version (using the latest is best).
