### ISSUE TITLE
Force Proxy Spawn

### ISSUE THREAD

**Issue by nucwin** [addstar/geSuit#13]
In spawns.yml when ForceAllPlayersToProxySpawn is true it fails to teleport people on join to the proxy's spawn point.

Thanks for continuing this project.

09:21:00 [INFO] Warning! Teleport called but player is null!
09:21:00 [SEVERE] java.lang.Exception:
09:21:00 [SEVERE]     at net.cubespace.geSuit.pluginmessages.TeleportToLocation.execute(TeleportToLocation.java:32)
09:21:00 [SEVERE]     at net.cubespace.geSuit.managers.SpawnManager.sendPlayerToProxySpawn(SpawnManager.java:38)
09:21:00 [SEVERE]     at net.cubespace.geSuit.listeners.SpawnListener.sendPlayerToHub(SpawnListener.java:19)
09:21:00 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:21:00 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:21:00 [SEVERE]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:21:00 [SEVERE]     at java.lang.reflect.Method.invoke(Method.java:483)
09:21:00 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
09:21:00 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
09:21:00 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
09:21:00 [SEVERE]     at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:466)
09:21:00 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
09:21:00 [SEVERE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
09:21:00 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
09:21:00 [SEVERE]     at java.lang.Thread.run(Thread.java:745)

**Comment by addstar** [comment]
Sorry but the more information you provide me, the better chance you'll have of getting someone to help you. Pasting an exception output with no context or explanation will most likely get ignored ;)

* What happened before this? Need more logs.
* Has this happened regularly or just this once?
* Which build are you running?
* What was the player doing at the time?
.....

**Comment by addstar** [comment]
Please re-open and provide more information (as mentioned above) if you want someone to help.

**Comment by nucwin** [comment]
sorry lack of context corrected ive corrected the top post

**Comment by addstar** [comment]
Which build of geSuit are you running?
And can you provide more logs from the actual login to the error (pastebin or similar please)

**Comment by addstar** [comment]
Sorry, I can't help without the info I asked for (twice now). Build version, full logs from the player login (proxy + server) and please use pastebin or similar.
