### ISSUE TITLE
tp

### ISSUE THREAD

**Issue by niftyapple** [addstar/geSuit#17]
In the latest release, it appears that the /HOME command places plates about 10-20 blocks below the intended destination. The database hold the correct Y value for the home but the telephone is not correct. Any other reports of this?

**Comment by addstar** [comment]
If the database holds the correct value, it's possible the "safe teleport" is taking effect. Can you confirm the home location is on solid ground? You can test the teleport by being flying and then trying to go home, this will bypass the safe teleport if it thinks you are off the ground. Have you tried just using /tp <x> <y> <z> and see if it does the same thing?

**Comment by niftyapple** [comment]
I can confirm that this is solid ground. Its not an every player issue and seems that the only few people that I know it has happened to have gone AFK. Feel free to close this out until I can investigate more.

**Comment by addstar** [comment]
Sorry, I can't think of any reason this could happen. If you can reproduce the problem every time, or find a pattern with it, provide as much info as you can and I can look into it.
