### ISSUE TITLE
Triple welcome announcement

### ISSUE THREAD

**Issue by Kainzo** [addstar/geSuit#20]
Below are the messages im seeing in console, on the server it seemed to only announce once, properly.

12:42:01 [INFO] Player ANSON1964114 (051b9fa0-12c1-4ca5-afe9-4a8b4b50a92f) connected from x.x.x.x
12:42:01 [INFO] [ANSON1964114] <-> ServerConnector [survival] has connected
12:42:02 [INFO] Created player ANSON1964114 (051b9fa0-12c1-4ca5-afe9-4a8b4b50a92f)
12:42:02 [INFO] Welcome ANSON1964114 to Herocraft for the first time!
12:42:02 [INFO] Welcome ANSON1964114 to Herocraft for the first time!
12:42:02 [INFO] Welcome ANSON1964114 to Herocraft for the first time!
12:42:02 [INFO] ANSON1964114 is from Central District, Hong Kong

**Comment by addstar** [comment]
Closing old issue, please let me know if this is still happening on the latest builds.
