### ISSUE TITLE
Ontime duplicated users.

### ISSUE THREAD

**Issue by Blackyvk** [addstar/geSuit#22]
I just noticed that the ontime sql table has thousand of records, and many are the same user like this

ea26bec876ec406c85ae1741214903c4	2015-03-24 22:00:00	3600

the only difference is the timeslot, why ?

**Comment by Schmoller** [comment]
The ontime table stores a history of player ontime. Because of this, there will be an entry added for every timeslot the player was online for, recording the amount of time the player was online during that timeslot.

**Comment by addstar** [comment]
Just to add a little context to this: It was done like this so we can run time-of-day reports for ontime usage. This can help identify possible staff candidates for particular times of the day. Don't worry it was designed to perform well even with millions of records in the table. I have some basic benchmark information in the original commit for the ontime tracking code: https://github.com/addstar/geSuit/commit/fb51a324c9ff7f3b11f322604f284e20f42c975c
