### ISSUE TITLE
Max tempban 6 days

### ISSUE THREAD

**Issue by Externalizable** [addstar/geSuit#24]
Hello!

While trying to tempban a User for longer than 1 month, the time has changed to 6 days while sending the Command.

Any way to solve this?

**Comment by addstar** [comment]
Can you tell me the command+syntax you are using, and please provide proxy logs at the time. Thanks.

**Comment by elliswin** [comment]
Hi Addstar,

 Im having a similar prob with geSuitbans im trying to temp ban a player for 30 days, im using the command /tempban <playername> 30d and its returning with player has been temporarily banned (0s). Reason Unknown.

 When I do a checkban it says he is tempban from 20 Jun 2015 23:29:30 BST until 01 Jun 2015 06:26:43 BST.

 Ive tested it with different amounts of time and it appears I cant ban anyone for any more than 24 days.

 Is there any way of changing this?

**Comment by addstar** [comment]
Bug Confirmed - Will work on a fix. Sorry for the delay.. we never tempban anyone for that long :wink: 
Thanks.

**Comment by Externalizable** [comment]
I found out by banning my Staff for fun, haha. :P

**Comment by addstar** [comment]
Hahaha.. nice one :grin:

**Comment by addstar** [comment]
Should now be fixed in [build #93](http://jenkins.addstar.com.au/job/geSuit/93/).

Thanks @Schmoller!! :+1:
