### ISSUE TITLE
(Suggestion) Suffix for Ban/Temp-Ban

### ISSUE THREAD

**Issue by Externalizable** [addstar/geSuit#26]
Hello!

When people get banned, they often worry about where to dispute. Maybe we could have an automatic line break where we could specify a Message and a Link to dispuse a Ban/Temp-Ban?

Cheers!

**Comment by addstar** [comment]
This is already possible.
You can use {N} in the "BAN_PLAYER_MESSAGE" or "TEMP_BAN_MESSAGE" text (messages.yml) to represent line breaks.
