### ISSUE TITLE
(Suggestion) Automatic ban for x warns

### ISSUE THREAD

**Issue by Externalizable** [addstar/geSuit#27]
Me again. Sorry, sorry.

Would you be able to integrate an automatic ban/temp-ban when a User reaches x warnings?

Cheers!

**Comment by addstar** [comment]
This is already possible, it is configured in the `bans.yml` file. Unfortunately it doesn't generate a default config. Here is an example of one we use. It should be fairly self explanatory:

```
Actions:
  2: kick
  3: tempban 30m
  4: tempban 45m
  5: tempban 1h
  6: tempban 2h
  7: tempban 3h
  8: tempban 12h
  9: tempban 24h
  10: ban
```

The above system will also take into account the `WarningExpiryDays` option and ignore any warnings prior to that age.
