### ISSUE TITLE
You are Already Online!

### ISSUE THREAD

**Issue by Blackyvk** [addstar/geSuit#28]
Sometimes players cannot connect to the server because... they are already online ? its weird

I think this problem is related to the problem we had once with the "PlayerDisconnectDelay: 0" (Because even today I still have that problem and people are online but are hidden for gesuit). I didnt notice we had this problem until I added global joins plugin and saw the lots of reconnections from players. and isnt that plugin fault since i checked logs and it was there before it.

http://hastebin.com/murazixoce.avrasm

**Comment by Absentee23** [comment]
Related: https://github.com/SpigotMC/BungeeCord/issues/1441
I'm testing the "FuckOff.jar" plugin Cory posted there, and so-far-so-good, but its only been ~12 hours at low traffic.

**Comment by Blackyvk** [comment]
thanks i'll try that jar...
