### ISSUE TITLE
Permission ? or bug ?

### ISSUE THREAD

**Issue by SheppeR** [addstar/geSuit#29]
Hi i am using a 1.8.3 spigot with
- geSuit build 90
- geSuitPortals build 4
- geSuitHomes build 13
- geSuitSpawns build 10
- geSuitWarps build 9

My problem is : 
When a player non OP pass over a portal for travel to a second server with portal type warp or server, player is not teleported from the server to the second server.
Editing permission change nothing.

hub server log:   http://pastebin.com/uPLPrYbs
server1 log:   http://pastebin.com/93Dsrs4k
server2 log:   http://pastebin.com/5z9e8wAX
proxy log:  http://pastebin.com/HyeasMTB

**Comment by addstar** [comment]
It looks like you have the same problem as issue #18. Please see it for more info.

When ever you see errors like "Unable to find player named..." or "Teleport called but player is null" then that player is not going to be able to use any geSuit functions and will need to reconnect.
